//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer2Material
    {
        public int PrinterId { get; set; }
        public string Material { get; set; }
        public bool IsGeneral { get; set; }
    
        public virtual PrintingMaterial PrintingMaterial { get; set; }
    }
}
