//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer2
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> MachineModeId { get; set; }
        public Nullable<int> AMProcessId { get; set; }
        public Nullable<int> AMTechnologyId { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public Nullable<int> YearRetired { get; set; }
        public Nullable<double> DimensionX { get; set; }
        public Nullable<double> DimensionY { get; set; }
        public Nullable<double> DimensionZ { get; set; }
        public Nullable<double> LayerMin { get; set; }
        public Nullable<double> LayerMax { get; set; }
        public Nullable<double> FocusDiameterMin { get; set; }
        public Nullable<double> FocusDiameterMax { get; set; }
        public Nullable<double> ScanningSpeedMax { get; set; }
        public Nullable<double> ScanningSpeedMin { get; set; }
        public string Power { get; set; }
        public Nullable<int> PrintheadNo { get; set; }
        public Nullable<double> FilamentDiameter { get; set; }
        public Nullable<double> Tolerance { get; set; }
        public Nullable<int> LasersNo { get; set; }
        public Nullable<int> LaserTypeId { get; set; }
        public Nullable<double> LaserWavelength { get; set; }
        public Nullable<double> MaxBeamPower { get; set; }
        public Nullable<int> OpenSourceId { get; set; }
        public Nullable<int> RestrictedId { get; set; }
        public Nullable<int> HeatedPlatformId { get; set; }
        public Nullable<int> ControlsId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string ImageUrl { get; set; }
    }
}
