//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterTechnology
    {
        public int PrinterId { get; set; }
        public string Remark { get; set; }
        public int TechnologyId { get; set; }
        public string Technology { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
