//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPrinter
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string MinLayerHeight { get; set; }
        public string MaxLayerHeight { get; set; }
        public Nullable<int> PrintingSpeed { get; set; }
        public string PrintingSpeedStr { get; set; }
        public string ObjectFile { get; set; }
        public string Color { get; set; }
        public Nullable<int> BuildVolume_W { get; set; }
        public Nullable<int> BuildVolume_H { get; set; }
        public Nullable<int> BuildVolume_D { get; set; }
        public string BuildVolume { get; set; }
        public Nullable<int> Min_LH { get; set; }
        public Nullable<int> Max_LH { get; set; }
        public string Materials { get; set; }
        public string Technologies { get; set; }
    }
}
