//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPrinter2Optic
    {
        public int PrinterId { get; set; }
        public int OpticId { get; set; }
        public string Remark { get; set; }
        public string Optic { get; set; }
    }
}
