//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCompanyPrinter
    {
        public int Id { get; set; }
        public int PrinterId { get; set; }
        public int CompanyId { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> MachineModeId { get; set; }
        public Nullable<int> AMProcessId { get; set; }
        public Nullable<int> AMTechnologyId { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public string PriceRange { get; set; }
        public Nullable<int> YearRetired { get; set; }
        public Nullable<double> DimensionX { get; set; }
        public Nullable<double> DimensionY { get; set; }
        public Nullable<double> DimensionZ { get; set; }
        public Nullable<double> DimensionXinch { get; set; }
        public Nullable<double> DimensionYinch { get; set; }
        public Nullable<double> DimensionZinch { get; set; }
        public Nullable<double> LayerMin { get; set; }
        public Nullable<double> LayerMax { get; set; }
        public Nullable<double> FocusDiameterMin { get; set; }
        public Nullable<double> FocusDiameterMininch { get; set; }
        public Nullable<double> FocusDiameterMax { get; set; }
        public Nullable<double> FocusDiameterMaxinch { get; set; }
        public Nullable<double> ScanningSpeedMax { get; set; }
        public Nullable<double> ScanningSpeedMaxinch { get; set; }
        public Nullable<double> ScanningSpeedMin { get; set; }
        public Nullable<double> ScanningSpeedMininch { get; set; }
        public Nullable<int> PrintheadNo { get; set; }
        public string Power { get; set; }
        public Nullable<double> FilamentDiameter { get; set; }
        public Nullable<double> Tolerance { get; set; }
        public Nullable<int> LasersNo { get; set; }
        public Nullable<int> LaserTypeId { get; set; }
        public Nullable<double> LaserWavelength { get; set; }
        public Nullable<double> MaxBeamPower { get; set; }
        public Nullable<int> OpenSourceId { get; set; }
        public Nullable<int> RestrictedId { get; set; }
        public Nullable<int> HeatedPlatformId { get; set; }
        public Nullable<int> ControlsId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Category { get; set; }
        public string Controls { get; set; }
        public string HeatedPlatform { get; set; }
        public string Restricted { get; set; }
        public string OpenSource { get; set; }
        public string LaserType { get; set; }
        public string AMProcess { get; set; }
        public string MachineMode { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string ManWebsite { get; set; }
        public int ManufacturerId { get; set; }
        public string MaterialsGeneral { get; set; }
        public string MaterialsSpecific { get; set; }
        public string AMTechnology { get; set; }
        public string Optics { get; set; }
        public string ManImageUrl { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public string DateVerifiedStr { get; set; }
        public int IsVerified { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public Nullable<bool> RushDelivery24 { get; set; }
        public Nullable<bool> RushDelivery48 { get; set; }
        public Nullable<int> PersonId { get; set; }
        public System.DateTime DateJoin { get; set; }
        public string DateJoinStr { get; set; }
        public Nullable<decimal> TotalRate { get; set; }
        public Nullable<int> TotalRateCount { get; set; }
        public string ZIPCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CountrySortName { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string Network { get; set; }
        public string ImageUrl { get; set; }
        public string ImageUrl2 { get; set; }
    }
}
